# Generated by Django 2.0 on 2018-01-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180103_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.CharField(default='', max_length=300),
        ),
    ]
