# Generated by Django 2.0 on 2018-01-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180103_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='notes',
            new_name='req_from',
        ),
        migrations.RemoveField(
            model_name='allocateditem',
            name='notes',
        ),
    ]
