# Generated by Django 2.0 on 2018-01-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180110_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateditem',
            name='request',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='webapp.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Request'),
        ),
    ]
