# Generated by Django 2.0 on 2018-01-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180113_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateditem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='webapp.Request'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='webapp.Request'),
        ),
    ]
