# Generated by Django 2.0 on 2018-01-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_allocateditem_purchase_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocateditem',
            name='purchase',
        ),
    ]
