# Generated by Django 2.0 on 2018-01-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_allocateditem_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateditem',
            name='purchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Purchase'),
            preserve_default=False,
        ),
    ]
